### ISSUE TITLE
Your code can't run because it is missing some necessary files. Could you please tell me where I can get these files?

### ISSUE THREAD

**Issue by ElvisChen7** [Skvayzer/Violence-Detector#1]
Thank u very much!

**Comment by Skvayzer** [comment]
> 

https://drive.google.com/file/d/1YuJB9I7F1plPab3vjmiwqkRH_c7-aVKQ/view?usp=sharing

There u go)
I guess you meant the openpose model weights.

**Comment by ElvisChen7** [comment]
Thank you very much for replying to my message so quickly!
But in the main.py file, the coding line `from yolov5 import YOLOv5` and `model_filename = 'helpmodels/mars-small128.pb'` indicates that the repository lacks these files such as 'YOLOv5' and 'helpmodels'.
I've been learning some new knowledge in the field of Yolo and DeepSort, but I still don't know how to deploy them in my code. So if you have the time, could you tell me where I can get the file, or how can I run your code?
My English is poor, so it's a little difficult for me to show how appreciative I am. If you don't have time, I'm still very thankful for your reply.
Wish you have a nice day : )

**Comment by Skvayzer** [comment]
I pushed some changes to the repo, git clone and try again. I changed in path names "helpmodels/" -> "models/". 
Also, you should pip install yolov5, i added it to requirements.txt. Hope these are the only problems left and everything's gonna work now(

**Comment by ElvisChen7** [comment]
Thank you for your reply, best wishes to you : ） ❤❤❤❤❤

**Comment by Skvayzer** [comment]
You're welcome, best wishes to you too)
By the way, i made this project based on this one:
https://github.com/TheAnkurGoswami/Human-Violence-Detection
There you can find a detailed report, it'll be helpful. I just made some modifications (switched to yolov5, draw skeletons, other stuff for the hackathon). And actually it works really slowly in the real-time, but there could be some improvements for the fps i guess.

And by the way, you are such a polite and nice person <3
